// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import HelloController from './hello_controller'
application.register('hello', HelloController)

import NoteModalController from './note_modal_controller'
application.register('note-modal', NoteModalController)

import ActivityModalController from './activity_modal_controller'
application.register('activity-modal', ActivityModalController)

import DatetimePickerController from './datetime_picker_controller'
application.register('datetime-picker', DatetimePickerController)

import CalendarLinksController from './calendar_links_controller'
application.register('calendar-links', CalendarLinksController)

import DropdownController from './dropdown_controller'
application.register('dropdown', DropdownController)
